# syntax=docker/dockerfile:1
FROM node:16 AS build
WORKDIR /react
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /react/build /usr/share/nginx/html

